// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glvrsykofsoubjhdyojp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsdnJzeWtvZnNvdWJqaGR5b2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDAzMTYsImV4cCI6MjA2MDYxNjMxNn0.PGMP5bC9SmBQFnz8HgL2erPqhReZLlLyDtAk0IHHBNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);